require_relative 'geometry/annulus'
require_relative 'geometry/arc'
require_relative 'geometry/circle'
require_relative 'geometry/line'
require_relative 'geometry/obround'
require_relative 'geometry/path'
require_relative 'geometry/point'
require_relative 'geometry/point_zero'
require_relative 'geometry/polygon'
require_relative 'geometry/polyline'
require_relative 'geometry/rectangle'
require_relative 'geometry/regular_polygon'
require_relative 'geometry/rotation'
require_relative 'geometry/size'
require_relative 'geometry/size_zero'
require_relative 'geometry/square'
require_relative 'geometry/transformation'
require_relative 'geometry/triangle'
require_relative 'geometry/vector'

module Geometry
end
